modLoader="javafml" 
loaderVersion="[41,)" 
license="MIT"
[[mods]]
modId="slurpmodtutorial" 
version="${file.jarVersion}" 
displayName="Battlepops"
logoFile="examplemod.png" 
credits="Credits go to slurpinpuffs and Lite."
authors="slurpinpuffs" 

description='''
A mod about edible and battle-ready lollipops.
'''
[[dependencies.slurpmodtutorial]] #optional
    modId="forge" 
    mandatory=true 
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.slurpmodtutorial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
